on: 
  push:
    branches:
    - 'main'    
name: Deploy to CDN
jobs:
  deploy:
    name: npm ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Set up s3cmd
      run: |
        python -m pip install --upgrade pip
        pip install s3cmd

    - name: sync folder with cdn
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CDN_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CDN_SECRET_ACCESS_KEY }}
      run: |
        s3cmd -c ./do/.s3cfg sync --acl-public ./build/ --delete-removed s3://api-docs --no-preserve --no-mime-magic --guess-mime-type -v 
    - name: purge cdn cache
      run: |
        doctl compute cdn flush 0375d09b-1263-4413-a455-dea4f028a3d2

